Lesson03/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.homepage),
    path('about/', views.about ),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls'))
]

#Telling APP where to find images
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Admin Password: rorisang99

Lesson03/myproject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name = "list"),
    path('new-post/', views.post_new, name = "new-post"),
    path('<slug:slug>', views.post_page, name = "page"),
]

Lesson03/myproject/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name = "register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

Lesson03/myproject/posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)

    def __str__(self):
        return self.title
    

Lesson03/myproject/users/models.py
from django.db import models

# Create your models here.

Lesson03/myproject/posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = [
            'title', 'body', 'slug', 'banner'
        ]

Lesson03/myproject/myproject/views.py
#from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')
#    return HttpResponse("Home page")
    

def about(request):
    return render(request, 'about.html')
#    return HttpResponse("My about page")

Lesson03/myproject/posts/views.py
from django.shortcuts import render
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by("-date")
    return render(request, 'posts/posts_list.html', {'posts': posts})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})

@login_required(login_url="/users/login/") #checks if user is logged, if not directs to login
def post_new(request):
    form = forms.CreatePost()
    return render(request, 'posts/post_new.html', {'form': form})

Lesson03/myproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
    else:   
        form = UserCreationForm()
    
    return render(request, "users/register.html", {"form": form})

def login_view(request):
    if request.method=="POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #Login here
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {"form": form} )

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:list")

Lesson03/myproject/posts/templates/posts/post_new.html
{% extends 'layout.html' %}
{% block title %}
  New Post
{% endblock %}
{% block content %}
  <section>
    <h1>New Post</h1>
    <form class="form-with-validation" action="" method="post">{{ form }}</form>
  </section>
{% endblock %}

Lesson03/myproject/posts/templates/posts/post_page.html
{% extends "layout.html" %} {% block title %} {{post.title}} {% endblock%}
{%block content %}
<section>
  <h1>{{post.title}}</h1>
  <p>{{post.date}}</p>
  <p>{{post.body}}</p>
  <img class="banner" src="{{post.banner.url}}" alt="{{post.title}}" />
</section>
{% endblock %}

Lesson03/myproject/posts/templates/posts/posts_list.html
{% extends "layout.html" %} {% block title %} Posts {% endblock %}
<hr />
{% block content %}
<section>
  <h1>Posts</h1>
  {% for post in posts %}
  <article class="post">
    <h2>
      <a href="{% url 'posts:page' slug=post.slug %}">{{post.title}}</a>
    </h2>
    <p>{{post.date}}</p>
    <p>{{post.body}}</p>
  </article>
  {% endfor %}
</section>

{% endblock %}

Lesson03/myproject/templates/about.html
{% extends "layout.html" %} {% block title %} About {% endblock %} 
<hr />
{% block content %}
<h1>About Page</h1>
<p>
  This who we are!
</p>

{% endblock %}

</html>

Lesson03/myproject/templates/home.html
{% extends "layout.html" %} {% block title %} Home {% endblock %}
<hr />
{% block content %}
<h1>Home Page</h1>
<p>
  Welcome to our page! Check out what we are <a href="/about">about</a> at Live!
</p>
{% endblock %}

Lesson03/myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Django App
      {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/main.js' %}" defer></script>
  </head>
  <body>
    <nav>
      <a href="/">Home</a> | <a href="/about">About</a> |
      <a href="{% url 'posts:list' %}">Posts</a> |{% if user.is_authenticated %}
        <a href="{% url 'posts:new-post' %}">New Post</a> |<form class="logout" action="{% url 'users:logout' %}" method="post">
          {% csrf_token %}
          <button class="logout-button">Logout</button>
        </form>
      {% else %}
        <a href="{% url 'users:register' %}">Register</a> |
        <a href="{% url 'users:login' %}">Login</a>
      {% endif %}
    </nav>
    <main>
      {% block content %}

      {% endblock %}
    </main>
  </body>
</html>

Lesson03/myproject/users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
  Login
{% endblock %}

{% block content %}
  <h1>Login Form</h1>
  <form class="form-with-validation" action="/users/login/" method="POST">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}" id="" />
    {% endif %}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

Lesson03/myproject/users/templates/users/register.html
{% extends 'layout.html' %} {% block title %}
  Register User
{% endblock %}
<hr />
{% block content %}
  <h1>Register new user</h1>
  <section>
    <form class="form-with-validation" action="/users/register/" method="POST">
      {% csrf_token %}
      {{ form }}
      <button type="Submit">Submit</button>
    </form>
  </section>
{% endblock %}